### ISSUE TITLE
Create a release for a critical bug fixed in issue 16, December 2016

### ISSUE THREAD

**Issue by edwardotis** [Grails-Plugin-Consortium/grails-jesque#19]
There was a critical bug fixed in this issue, but no subsequent tag or release to repo.
https://github.com/Grails-Plugin-Consortium/grails-jesque/issues/16

Can a contributor make a tag and release with this fix?

Thanks!

**Comment by ctoestreich** [comment]
I released v1.2.1

**Comment by rationalsales** [comment]
Thanks!
